// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtkqdevyaliybacjcbwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0a3FkZXZ5YWxpeWJhY2pjYndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDIyODYsImV4cCI6MjA3MjAxODI4Nn0.C5kVluv9BvaVWquLqJFgGQ_R-e8-EOaiv039YgCuwXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});